modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="busutilities"
version="1.1.1"
displayName="NewBusUtilities"
credits="Principal mod du Projet MCB"
displayURL="https://github.io/MC-Bus/MCB-BusUtilities"
authors="BlocBlocTheBloc"

[[dependencies.busutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




